#!/usr/bin/env bash

for x in apparmor_add_profile pattern-public-cloud apparmor_app_armor pattern-x11 apparmor_delete_profile pattern-xfce apparmor_edit_profile suse apparmor_view_profile yast-audit-laf fcoe yast-device-mapper gnome yast-device-tree kde yast-dump pattern-adv-sys-mgmt yast-files pattern-apparmor yast-geo-cluster pattern-basis-devel yast-gray-dot pattern-basis yast-green-dot pattern-documentation yast-hardware pattern-e17 yast-hdd-controller-kernel-module pattern-enlightenment yast-iplb pattern-generic yast-live-install-finish pattern-gnome-devel yast-partitioning pattern-gnome-laptop yast-red-dot pattern-gnome yast-reipl pattern-kde4 yast-report pattern-kde-devel yast-restore pattern-kde-laptop yast-scripts pattern-kde yast-SMT pattern-kernel yast-support pattern-LAMP yast pattern-laptop yast-tftp-server pattern-lxde yast-unused-device pattern-mate yast-xpram pattern-mono yast-yellow-dot pattern-network yast-you_server
do
  inkscape -z --export-png Origami/16x16/apps/${x}.png Origami/16x16/apps/${x}.svg
done
for x in apparmor_add_profile yast-joystick apparmor_app_armor yast-kdump apparmor_delete_profile yast-kerberos apparmor_edit_profile yast-keyboard apparmor_view_profile yast-kiwi fcoe yast-language gnome yast-lan kde yast-ldap-browser pattern-adv-sys-mgmt yast-ldap-server pattern-apparmor yast-ldap pattern-basis-devel yast-license pattern-basis yast-live-install-finish pattern-documentation yast-live-install pattern-enlightenment yast-lvm_config pattern-generic yast-mail-server pattern-gnome-devel yast-mail pattern-gnome-laptop yast-messages pattern-gnome yast-misc pattern-kde4 yast-modem pattern-kde-devel yast-mouse pattern-kde-laptop yast-network_devices pattern-kde yast-network_services pattern-kernel yast-network pattern-LAMP yast-nfs_server pattern-laptop yast-nfs pattern-lxde yast-nis_server pattern-mate yast-nis pattern-mono yast-ntp-client pattern-network yast-online_update pattern-public-cloud yast-onpanic pattern-x11 yast-partitioning pattern-xfce yast-powertweak suse yast-printer yast-addon yast-product-registration yast-audit-laf yast-provider yast-autoyast yast-proxy yast-backup yast-raid yast-bluetooth yast-red-dot yast-bootloader yast-reipl yast-ca_mgm yast-release-notes yast-cd-creator yast-remotechooser yast-cd_update yast-remoteinstall yast-certify yast-remote yast-checkmedia yast-report yast-common_cert yast-restore yast-controller yast-routing yast-create-new-vm yast-runlevel yast-dasd yast-samba-client yast-default-group yast-samba-server yast-deploy_image yast-scanner yast-desktop-select yast-scripts yast-device-mapper yast-security yast-device-tree yast-slp-server yast-dhcp-server yast-SMT yast-disk yast-snapper yast-dns-server yast-software yast-dns yast-sound yast-dsl yast-spanner yast-dump yast-squid yast-encrypted yast-ssh-server yast-files yast-sudo yast-firewall yast-support yast-firstboot yast yast-ftp-server yast-sw_single yast-general yast-sw_source yast-geo-cluster yast-sysconfig yast-gray-dot yast-system yast-green-dot yast-system-user yast-hardware yast-tftp-server yast-hdd-controller-kernel-module yast-timezone yast-heartbeat yast-tv yast-high_availability yast-uml yast-host yast-unused-device yast-http-server yast-update yast-hwinfo yast-users yast-inetd yast-vendor yast-inst-mode yast-vm-install yast-instserver yast-vm-management yast-iplb yast-wol yast-iscsi-client yast-x11 yast-iscsi-server yast-xpram yast-isdn yast-yellow-dot yast-isns yast-you_server yast-iucvterminal-server yast-zfcp yast-iucvterminal
do
  inkscape -z --export-png Origami/22x22/apps/${x}.png Origami/22x22/apps/${x}.svg
done
for x in apparmor_add_profile yast-isns apparmor_app_armor yast-iucvterminal-server apparmor_delete_profile yast-iucvterminal apparmor_edit_profile yast-joystick apparmor_view_profile yast-kdump disk-utility yast-kerberos fcoe yast-keyboard gnome yast-kiwi kde yast-language msg_error yast-lan msg_info yast-ldap-browser msg_question yast-ldap-server msg_warning yast-ldap pattern-adv-sys-mgmt yast-license pattern-apparmor yast-live-install-finish pattern-basis-devel yast-live-install pattern-basis yast-lvm_config pattern-documentation yast-mail-server pattern-enlightenment yast-mail pattern-generic yast-messages pattern-gnome-devel yast-misc pattern-gnome-laptop yast-modem pattern-gnome yast-mouse pattern-kde4 yast-network_devices pattern-kde-devel yast-network_services pattern-kde-laptop yast-network pattern-kde yast-nfs_server pattern-kernel yast-nfs pattern-LAMP yast-nis_server pattern-laptop yast-nis pattern-lxde yast-ntp-client pattern-mate yast-online_update pattern-mono yast-onpanic pattern-network yast-partitioning pattern-public-cloud yast-powertweak pattern-x11 yast-printer pattern-xfce yast-product-registration suse yast-provider yast-addon yast-proxy yast-audit-laf yast-raid yast-autoyast yast-reipl yast-backup yast-release-notes yast-bluetooth yast-remotechooser yast-bootloader yast-remoteinstall yast-ca_mgm yast-remote yast-cd-creator yast-report yast-cd_update yast-restore yast-certify yast-routing yast-checkmedia yast-runlevel yast-common_cert yast-samba-client yast-controller yast-samba-server yast-create-new-vm yast-scanner yast-dasd yast-scripts yast-default-group yast-security yast-deploy_image yast-slp-server yast-desktop-select yast-SMT yast-device-mapper yast-snapper yast-device-tree yast-software yast-dhcp-server yast-sound yast-disk yast-spanner yast-dns-server yast-squid yast-dns yast-ssh-server yast-dsl yast-sudo yast-dump yast-support yast-encrypted yast yast-files yast-sw_single yast-firewall yast-sw_source yast-firstboot yast-sysconfig yast-ftp-server yast-system yast-general yast-system-user yast-geo-cluster yast-tftp-server yast-hardware yast-timezone yast-hdd-controller-kernel-module yast-tv yast-heartbeat yast-uml yast-high_availability yast-unused-device yast-host yast-update yast-http-server yast-users yast-hwinfo yast-vendor yast-inetd yast-vm-install yast-inst-mode yast-vm-management yast-instserver yast-wol yast-iplb yast-x11 yast-iscsi-client yast-xpram yast-iscsi-server yast-you_server yast-isdn yast-zfcp
do
  inkscape -z --export-png Origami/32x32/apps/${x}.png Origami/32x32/apps/${x}.svg
done
for x in apparmor_add_profile yast-joystick apparmor_app_armor yast-kdump apparmor_delete_profile yast-kerberos apparmor_edit_profile yast-keyboard apparmor_view_profile yast-kiwi fcoe yast-language gnome yast-lan kde yast-ldap-browser pattern-adv-sys-mgmt yast-ldap-server pattern-apparmor yast-ldap pattern-basis-devel yast-license pattern-basis yast-live-install-finish pattern-documentation yast-live-install pattern-enlightenment yast-lvm_config pattern-generic yast-mail-server pattern-gnome-devel yast-mail pattern-gnome-laptop yast-messages pattern-gnome yast-misc pattern-kde4 yast-modem pattern-kde-devel yast-mouse pattern-kde-laptop yast-network_devices pattern-kde yast-network_services pattern-kernel yast-network pattern-LAMP yast-nfs_server pattern-laptop yast-nfs pattern-lxde yast-nis_server pattern-mate yast-nis pattern-mono yast-ntp-client pattern-network yast-online_update pattern-public-cloud yast-onpanic pattern-x11 yast-partitioning pattern-xfce yast-powertweak suse yast-printer yast-addon yast-product-registration yast-audit-laf yast-provider yast-autoyast yast-proxy yast-backup yast-raid yast-bluetooth yast-red-dot yast-bootloader yast-reipl yast-ca_mgm yast-release-notes yast-cd-creator yast-remotechooser yast-cd_update yast-remoteinstall yast-certify yast-remote yast-checkmedia yast-report yast-common_cert yast-restore yast-controller yast-routing yast-create-new-vm yast-runlevel yast-dasd yast-samba-client yast-default-group yast-samba-server yast-deploy_image yast-scanner yast-desktop-select yast-scripts yast-device-mapper yast-security yast-device-tree yast-slp-server yast-dhcp-server yast-SMT yast-disk yast-snapper yast-dns-server yast-software yast-dns yast-sound yast-dsl yast-spanner yast-dump yast-squid yast-encrypted yast-ssh-server yast-files yast-sudo yast-firewall yast-support yast-firstboot yast yast-ftp-server yast-sw_single yast-general yast-sw_source yast-geo-cluster yast-sysconfig yast-gray-dot yast-system yast-green-dot yast-system-user yast-hardware yast-tftp-server yast-hdd-controller-kernel-module yast-timezone yast-heartbeat yast-tv yast-high_availability yast-uml yast-host yast-unused-device yast-http-server yast-update yast-hwinfo yast-users yast-inetd yast-vendor yast-inst-mode yast-vm-install yast-instserver yast-vm-management yast-iplb yast-wol yast-iscsi-client yast-x11 yast-iscsi-server yast-xpram yast-isdn yast-yellow-dot yast-isns yast-you_server yast-iucvterminal-server yast-zfcp yast-iucvterminal
do
  inkscape -z --export-png Origami/48x48/apps/${x}.png Origami/48x48/apps/${x}.svg
done
for x in apparmor_app_armor yast-kerberos bootdisk_create yast-keyboard fcoe yast-kiwi gnome yast-lan kde yast-ldap-browser keyboardlayout yast-ldap-server ktip yast-ldap msg_error yast-license msg_info yast-live-install msg_warning yast-lvm_config pattern-adv-sys-mgmt yast-mail-server pattern-enlightenment yast-mail pattern-gnome-devel yast-messages pattern-gnome yast-misc pattern-kde4 yast-modem pattern-kde yast-mouse pattern-lxde yast-network_devices pattern-mate yast-network_services pattern-public-cloud yast-network pixie yast-nfs_server printer2 yast-nfs route yast-nis_server samba_setup yast-nis SuSEmenu yast-ntp-client system yast-online_update tdsl yast-onpanic user_add yast-powertweak user_system yast-printer www yast-product-registration yast-addon yast-provider yast-autoyast yast-proxy yast-backup yast-release-notes yast-bluetooth yast-remote yast-bootloader yast-restore yast-ca_mgm yast-routing yast-cd-creator yast-samba-client yast-cd_update yast-samba-server yast-checkmedia yast-scanner yast-common_cert yast-security yast-controller yast-slp-server yast-create-new-vm yast-snapper yast-dasd yast-software yast-dhcp-server yast-sound yast-disk yast_source yast-dns-server yast-ssh-server yast-dns yast-sudoers yast-dsl yast-support yast-dump yast yast-firewall yast-sw_single yast-ftp yast-sw_source yast-geo-cluster yast-sysconfig yast-hardware yast-system yast-heartbeat yast-tftp-server yast-high_availability yast-timezone yast-host yast-tv yast-http-server yast-uml yast-hwinfo yast-update yast-inetd yast-vdisk yast-inst-mode yast-vendor yast-instserver yast-virtualisation yast-iplb yast-vm-domain0-setup yast-iscsi-client yast-vm-install yast-iscsi-server yast-vm-management yast-isdn yast-wol yast-isns yast-x11 yast-iucvterminal-server yast-xpram yast-iucvterminal yast-yast-language yast-joystick yast-zfcp yast-kdump
do
  inkscape -z --export-png Origami/64x64/apps/${x}.png Origami/64x64/apps/${x}.svg
done
